[tool.mypy]
[[tool.mypy.overrides]]
module = [
    'genshi.template',
    'geopandas',
    'matplotlib',
    'matplotlib.*',
    'pandas',
    'rasterio',
    'rasterio.*',
    'scipy.*',
    'shapely',
    'shapely.*',
    'skimage',
    'skimage.*',
    'sklearn.*',
    'sqlalchemy',
    'sqlalchemy.*',
    'tifftools',
]
ignore_missing_imports = true
