[tool.mypy]
[[tool.mypy.overrides]]
module = [
    'genshi.template',
    'geopandas',
    'pandas',
    'rasterio',
    'rasterio.*',
    'shapely',
    'shapely.*',
    'skimage',
    'skimage.*',
    'sklearn.*',
    'tifftools',
    
]
ignore_missing_imports = true

